[project]
name = "assetto-minimap"
version = "0.2.0b13"
description = "Waze/GPS Minimap and Telemetry companion for Assetto Corsa & Shutoko Revival Project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.28.0",
    "websockets>=12.0",
    "pillow>=10.2.0",
    "qrcode>=7.4.2",
]

[tool.uv]
package = false

[dependency-groups]
build = [
    "pyinstaller>=6.11,<7",
]
