import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(scriptDirectory, "..");

const projectManifest = JSON.parse(
  await readFile(path.join(repositoryRoot, "package.json"), "utf8")
);
const version = projectManifest.version;

let commit = "unknown";
try {
  commit = execFileSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: repositoryRoot,
    encoding: "utf8",
  }).trim();
} catch {
  // Building from a source tree without git history (e.g. a downloaded
  // archive) - fall back to "unknown" rather than failing the build.
}

const outputPath = path.join(repositoryRoot, "frontend", "src", "version.ts");
const contents = `// Generated by scripts/generate_frontend_version.mjs - do not edit.
window.appVersion = ${JSON.stringify(version)};
window.appCommit = ${JSON.stringify(commit)};
`;

await writeFile(outputPath, contents);
